version: "3.9"
  
services:

  fastapi_service:
    build:
      context: ./fastapi_backend
      dockerfile: Dockerfile
    hostname: fastapi_backend_container
    container_name: fastapi_backend_container
    depends_on:
      - db_postgres
      - broker_kafka
    ports:
      - "8085:8085"
    networks:
      - task-management-app-network
    volumes:
      - ./fastapi_backend:/app #Sync local directory with the container directory
  

  db_postgres:
    image: postgres:alpine
    hostname: fastapi-postgres
    container_name: fastapi-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_db
    ports:
      - "5432:5432"
    networks:
      - task-management-app-network
    volumes:
      - db_postgres:/var/lib/postgresql/data


  broker_kafka:
    image: bitnami/kafka
    hostname: broker_kafka
    container_name: broker_kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker_kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CFG_LISTENERS: CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@broker_kafka:29093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAME: CONTROLLER
      KAFKA_LOG_DIR: /tmp/kraft-combined-logs
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      - task-management-app-network


  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    depends_on:
      - broker_kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: Local kafka Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker_kafka:19092
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - task-management-app-network
    

volumes:
  db_postgres:
    driver: local


networks:
  task-management-app-network:
    external: true